groups: []
resources:
- name: charts
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
    paths:
    - stable/redis/**
    - stable/sentry/**
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-sentry
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: deploy-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: charts
    - get: deploy-src
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        DEPLOY_ENV: ci
        EMAIL_FROM_ADDRESS: ((email_from_address))
        EMAIL_HOST: ((email_host))
        EMAIL_PORT: ((email_port))
        EMAIL_USER: ((email_user))
        EMAIL_PASSWORD: ((email_password))
        EMAIL_USE_TLS: "YES"
        GITHUB_APP_ID: ((github_app_id))
        GITHUB_API_SECRET: ((github_api_secret))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        KUBECONFIG: ((kubeconfig))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        DEPLOY_ENV: ci
        KUBECONFIG: ((kubeconfig))
- name: delete-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: delete
      file: deploy-src/ci/delete.yml
      params:
        KUBECONFIG: ((kubeconfig))
        NAMESPACE: sentry-ci
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-prod
  serial: true
  plan:
  - do:
    - get: charts
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        DEPLOY_ENV: prod
        EMAIL_FROM_ADDRESS: ((email_from_address))
        EMAIL_HOST: ((email_host))
        EMAIL_PORT: ((email_port))
        EMAIL_USER: ((email_user))
        EMAIL_PASSWORD: ((email_password))
        EMAIL_USE_TLS: "YES"
        GITHUB_APP_ID: ((github_app_id))
        GITHUB_API_SECRET: ((github_api_secret))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        KUBECONFIG: ((kubeconfig))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        DEPLOY_ENV: prod
        KUBECONFIG: ((kubeconfig))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
