groups: []
resources:
- name: sentry-chart
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
    paths:
    - stable/sentry/**
- name: redis-chart
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-sentry
- name: 7pm
  type: time
  source:
    start: 7:00 PM
    stop: 8:00 PM
    location: Australia/Sydney
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: deploy-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: redis-chart
      version:
        # We dont want to keep redis up to date until we are
        # really sure we wont lose data, so it is pinned
        ref: "a83f5be3b228389177271ffb6c74c4308f8d678c"
    - get: sentry-chart
    - get: deploy-src
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ADMIN_EMAIL: ((ADMIN_EMAIL))
        BOOTSTRAP_USER_EMAIL: ((BOOTSTRAP_USER_EMAIL))
        BOOTSTRAP_USER_PASSWORD: ((BOOTSTRAP_USER_PASSWORD))
        DB_PLAN: dev
        DEPLOY_ENV: ci
        EMAIL_FROM_ADDRESS: ((email_from_address))
        EMAIL_HOST: ((email_host))
        EMAIL_PORT: ((email_port))
        EMAIL_USER: ((email_user))
        EMAIL_PASSWORD: ((email_password))
        GITHUB_APP_ID: ((github_app_id))
        GITHUB_API_SECRET: ((github_api_secret))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        OIDC_AUTHORIZATION_ENDPOINT: ((oidc_authorization_endpoint))
        OIDC_CLIENT_ID: ((oidc_client_id_ci))
        OIDC_CLIENT_SECRET: ((oidc_client_secret_ci))
        OIDC_ISSUER: ((oidc_issuer))
        OIDC_SCOPE: ((oidc_scope))
        OIDC_TOKEN_ENDPOINT: ((oidc_token_endpoint))
        OIDC_USERINFO_ENDPOINT: ((oidc_userinfo_endpoint))
        KUBECONFIG: ((kubeconfig))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        DEPLOY_ENV: ci
        KUBECONFIG: ((kubeconfig))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: delete-ci
  serial_groups:
  - ci
  plan:
  - do:
    - get: deploy-src
      passed:
      - deploy-ci
    - get: 7pm
      trigger: true
    - task: delete
      file: deploy-src/ci/delete.yml
      params:
        DEPLOY_ENV: ci
        KUBECONFIG: ((kubeconfig))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: deploy-prod
  serial: true
  plan:
  - do:
    - get: redis-chart
      passed:
      - deploy-ci
    - get: sentry-chart
      passed:
      - deploy-ci
    - get: deploy-src
      passed:
      - deploy-ci
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        ADMIN_EMAIL: ((ADMIN_EMAIL))
        DEPLOY_ENV: prod
        EMAIL_FROM_ADDRESS: ((email_from_address))
        EMAIL_HOST: ((email_host))
        EMAIL_PORT: ((email_port))
        EMAIL_USER: ((email_user))
        EMAIL_PASSWORD: ((email_password))
        GITHUB_APP_ID: ((github_app_id))
        GITHUB_API_SECRET: ((github_api_secret))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        OIDC_AUTHORIZATION_ENDPOINT: ((oidc_authorization_endpoint))
        OIDC_CLIENT_ID: ((oidc_client_id_prod))
        OIDC_CLIENT_SECRET: ((oidc_client_secret_prod))
        OIDC_ISSUER: ((oidc_issuer))
        OIDC_SCOPE: ((oidc_scope))
        OIDC_TOKEN_ENDPOINT: ((oidc_token_endpoint))
        OIDC_USERINFO_ENDPOINT: ((oidc_userinfo_endpoint))
        POSTGRES_DB_NAME: ((POSTGRES_DB_NAME_PROD))
        POSTGRES_ENDPOINT_ADDRESS: ((POSTGRES_ENDPOINT_ADDRESS_PROD))
        POSTGRES_MASTER_PASSWORD: ((POSTGRES_MASTER_PASSWORD_PROD))
        POSTGRES_MASTER_USERNAME: ((POSTGRES_MASTER_USERNAME_PROD))
        POSTGRES_PORT: ((POSTGRES_PORT_PROD))
        KUBECONFIG: ((kubeconfig))
    - task: smoke-test
      file: deploy-src/ci/smoke-test.yml
      params:
        DEPLOY_ENV: prod
        KUBECONFIG: ((kubeconfig))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME SUCCESS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
