groups: []
resources:
- name: src
  type: git
  source:
    branch: master
    uri: https://github.com/helm/charts
- name: deploy-src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-deploy-sentry
# - name: slack
#   type: slack-notification
#   source:
#     url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: deploy-ci
  serial: true
  plan:
  - do:
    - get: src
    - get: deploy-src
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        KUBECONFIG: ((kubeconfig))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        NAMESPACE: sentry-ci
        VALUES_FILE: values-ci.yml
- name: delete-ci
  serial: true
  plan:
    - do:
      - get: src
        passed:
        - deploy-ci
        trigger: true
      - get: deploy-src
        passed:
        - deploy-ci
        trigger: true
      - task: deploy
        file: deploy-src/ci/delete.yml
        params:
          KUBECONFIG: ((kubeconfig))
          NAMESPACE: sentry-ci
          VALUES_FILE: values-ci.yml
- name: deploy-prod
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - deploy-ci
      trigger: true
    - get: deploy-src
      passed:
      - deploy-ci
      trigger: true
    - task: deploy
      file: deploy-src/ci/deploy.yml
      params:
        KUBECONFIG: ((kubeconfig))
        GOOGLE_CLIENT_ID: ((google_client_id))
        GOOGLE_CLIENT_SECRET: ((google_client_secret))
        NAMESPACE: sentry
        VALUES_FILE: values.yml

